### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by epicarts** [innovationacademy-kr/swlabs-helper#16]
기술스택, 프로젝트의 사용목적, 사용법 등 프로젝트에 대한 설명이 적혀있는 문서를 작성해야한다.

도움이 될만한 링크: https://naver.github.io/OpenSourceGuide/book/OpenYourProject/starting-an-open-source-project.html

**Comment by Belnut** [comment]
예시 링크 : https://github.com/RichardLitt/standard-readme

**Comment by Belnut** [comment]
Contibuting.md 문서

1. 어떻게 Pull Request가 이루어지는가? (요청시 주의점, 변경사항에 대한 README 기록 여부 및 방식, 관리, merge 기준)
2. 어떤 규칙이 있는가? (코드 규칙, 토론 중 지켜야 할 매너 등)
3. 해당 프로젝트는 어떻게 사용되는가? (공공 or 사적, 개인 or 특정단체 or 광범위)
4. 관리자는 어디까지 관여하고, 프로젝트 수정시 어느범위까지 공개하고 어떻게 공유하는가?.

**Comment by Belnut** [comment]
타 프로젝트 예시)
Spring-boot petclinic - https://github.com/spring-projects/spring-petclinic

Spring-boot 학습 예시 프로젝트
클론 및 빌드 방법, 
로컬 실행방법, 로컬 환경설정 방법
사용가능한 IDE 와 설정방법
기여방법
라이센스

위의 항목이 기록되어 있으며

기여방법에는 어떤방식으로 이슈를 관리하는지, 
pull request전에 해야할 행동 (해당 프로젝트는 Contributor License Agreement를 요구) 를 제시한다.

**Comment by platanus-kr** [comment]
머지할 정도는 아니지만 우리 개발환경에 대해서 일부 작성해 올려봅니다.
https://www.notion.so/epicarts2/b49a93e4b4db41cdba25ff1848fee812
