### ISSUE TITLE
[외부피드백] 멘토로 팀 생성후 탈퇴 가능 및 탈퇴시 팀 잔존

### ISSUE THREAD

**Issue by platanus-kr** [innovationacademy-kr/swlabs-helper#224]
### 문제
멘토로 팀 생성후 탈퇴 가능 및 바로 탈퇴시 0명짜리 팀 잔존

### 증상 재현 방법
1. **멘토 신청 - 멘토링하기 (멘토)** 로 멘토링 팀 만든다
2. **팀 목록 - 내가 속한 팀 - 탈퇴** 버튼 누르기
3. **팀 목록 - 모든 팀** 에 가보면 0명 팀이 생성됨

### 사이드 이팩트
- 0명짜리 팀에는 멘토가 참가할 수 없습니다. 참가시 멘티로만 참가가 됩니다.

이하 피드백 원문입니다.
- - -
멘토로 생성하고 바로 탈퇴 눌러봤더니 탈퇴가 되어요..! (팀 목록 - 모든 팀)멘토 미지정에 인원 0명으로 프로젝트가 남아있길래 다시 신청해보니까 멘토가 아니라 멘티로 들어가지네요
+) 멘토링을 생성한 경우가 아니라 만들어진 멘토링에 멘토로 참여한 경우도 탈퇴 가능합니다

**Comment by platanus-kr** [comment]
thymeleaf쪽에서 막을 수 있을것 같아서 일단 제가 가져가보겠습니다.

**Comment by Belnut** [comment]
백엔드에서도 해당 작업이 필요합니다.
