### ISSUE TITLE
Github action CD 작성

### ISSUE THREAD

**Issue by epicarts** [innovationacademy-kr/swlabs-helper#24]
main 브런치에 merge 이벤트가 발생할 시(혹은 생각하는 다른 이벤트) aws 서버에 자동으로 배포가 되어야한다.

해당이슈는 이슈: #23 에 의존성이 있다.

**Comment by platanus-kr** [comment]
로컬 저장소 위치를 정해야 할 것 같습니다.
`~/git/swlabs-helper` 나 `~/git/server` 정도가 적당할 것 같습니다.

**Comment by epicarts** [comment]
git 폴더에 계속 코드를 유지한다면`~/git/swlabs-helper`가 적당할거 같습니다. 그 외에 경로라면 새로 네이밍 하는 것도 좋은거 같아요.
