### ISSUE TITLE
[#253 에 관련된 추가 제안] 팀 상세보기에서 팀원 아이디 링크하면 profile.intra.42.fr/users/로 연결

### ISSUE THREAD

**Issue by seongcho1** [innovationacademy-kr/swlabs-helper#256]
나의팀의 상세보기에서는 나의 팀원의 상세 정보를 볼수 있도록 
팀원 아이디를 클릭하면 profile.intra.42.fr/users/로 연결되는 기능도 좋을 것 같아요..

**Comment by Belnut** [comment]
의견 감사합니다!

**Comment by platanus-kr** [comment]
제안 주셔서 감사합니다. 의견 반영하여 금일 배포에 적용했습니다. 다시한번 의견 감사합니다.
