### ISSUE TITLE
[Bug] 멘토, 멘티 신청 모달 UI

### ISSUE THREAD

**Issue by padawanR0k** [innovationacademy-kr/swlabs-helper#289]
## 발생 이슈
- 캘린더 UI가 보여지고 있을때 모달을 닫게되면 UI가 그대로 남아있음

## 발생위치
- https://helper.42seoul.io/mentor
- https://helper.42seoul.io/mentee

## 참고 이미지
![image](https://user-images.githubusercontent.com/35283339/126285691-c124f29b-808b-4366-992f-a5d8ca0b19d4.png)

**Comment by Belnut** [comment]
제보 감사합니다! modal 창이 닫힐 때 자동으로 닫도록 수정하겠습니다.
