### ISSUE TITLE
오타 

### ISSUE THREAD

**Issue by kenu** [innovationacademy-kr/swlabs-helper#292]
`죵료된 멘토링`
오타있습니다.
![스크린샷 2021-07-22 오전 7 58 30](https://user-images.githubusercontent.com/718691/126570425-b0678260-7008-4fb2-90db-1986d9306b5a.png)

**Comment by Belnut** [comment]
네! 확인했습니다. 오늘 중으로 
오늘 한번 다시 확인해보면서 오타가 있는지 찾아 봐야겠습니다.
