### ISSUE TITLE
[Bug] [View] column 여백이 서로 안맞아요!

### ISSUE THREAD

**Issue by 42mypark** [innovationacademy-kr/swlabs-helper#371]
**Describe the bug**
인덱스의 칼럼 여백이 서로 맞지 않습니다.

**To Reproduce**
1. Go to '팀 목록'
2. Click on '나의팀 - 다른팀'

**Expected behavior**
인덱스의 칼럼 여백이 서로 맞음.

**Screenshots**

![Screenshot from 2021-11-26 00-01-59](https://user-images.githubusercontent.com/56795942/143464809-9e50a7ad-fd4e-4afa-ad8b-c1910ba271e1.png)

![Screenshot from 2021-11-26 00-02-08](https://user-images.githubusercontent.com/56795942/143464822-b086996c-7555-487d-b46f-44db1291b59f.png)

**Additional context**

이런 거 적어도 되죠..?

**Comment by Belnut** [comment]
제보 감사합니다!
어떤 것이라도 환영합니다! 

확인해보고 수정하겠습니다
