### ISSUE TITLE
삭제 버튼보다 상세보기 버튼이 조금 더 편할 것 같아요!

### ISSUE THREAD

**Issue by 42mypark** [innovationacademy-kr/swlabs-helper#372]
**Is your feature request related to a problem? Please describe.**
42helper의 멘티 신청 기능을 사용해, [멘티 신청] 페이지에서 멘토링을 신청해 보았습니다.
[멘티 신청] 페이지의 [내가 만든 멘토링 목록] 보면서, '내가 신청한 멘토링의 세부사항은 어떻게 확인하지?' 라는 생각이 들어서
기능을 찾아야하는 번거로움이 생기는 것 같습니다.

**Describe the solution you'd like**
[삭제] 버튼을 [상세보기] 버튼으로 바꾸어 주시면 이용자가 해당 기능을 찾는 수고를 덜 수 있을 것 같습니다.

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2021-11-26 00-11-07](https://user-images.githubusercontent.com/56795942/143466501-2f4720ac-4619-4240-be14-dc6b534ebf93.png)

**Comment by plan5886** [comment]
버튼과 가운데 정렬도 부탁드려요!!

**Comment by Belnut** [comment]
의견 감사드립니다!

이전 해당 기능 구현시 세부사항으로 기능을 바꾸는 것이 좋을까? 라는 생각이 들긴 하지만 팀 목록에서 자신의 팀을 볼 수 있기에 내용이 중복되어
간단히 추가 삭제할 수 있게끔 제작하였습니다.
버튼을 교체하는 것은 어렵지 않으나 조금 고민해봐야 할 것 같습니다!
