### ISSUE TITLE
[Bug] [View] 페이지 전체의 좌측 우측 마진이 안맞습니다.

### ISSUE THREAD

**Issue by 42mypark** [innovationacademy-kr/swlabs-helper#373]
**Describe the bug**
전체화면일 때에는 잘 맞으나 브라우저의 크기를 줄이면,
비교적 작은 크기일 때, 홈-멘티신청-멘토신청 페이지의 좌우 여백은 동일하지만, 
팀목록 페이지의 좌우 여백은 세 페이지와 조금 다릅니다.
또, 비교적 중간 크기일 때, 
홈-멘토신청 페이지의 좌우 여백과 멘티신청-팀목록 페이지의 좌우 여백이 조금 다릅니다.

상단의 맨 위의 줄을 보시면 쉽게 파악가능합니다.
크롬 브라우저를 이용했습니다.

**Comment by Belnut** [comment]
여러 제보 감사합니다!

단 UI에 관련되서는 제가 너무 약해서 반영이 늦어질 수 있습니다 ㅠ
주말에 한번 확인해보겠습니다!
