### ISSUE TITLE
Login 속도 개선을 위한 Google OAuth 계정 연동

### ISSUE THREAD

**Issue by epicarts** [innovationacademy-kr/swlabs-helper#50]
42 intra 에 연결하여 로그인하는 방식은 시간이 응답 시간이 오래걸린다.

이에 대한 해결방법으로 42 계정이 연결되어 있는 상태에서 Google OAuth 로그인을 연동하여, 로그인 속도 향상을 기대할 수 있다.

**Comment by Belnut** [comment]
음... 
42계정이 있다면 그 상태에서 구글 계정을 연결하고 구글로 로그인할 수 있게 하자는 말씀이신가요?

**Comment by epicarts** [comment]
네네 맞습니다. 42계정이 선행되는것으로 생각하고 있어요.
