### ISSUE TITLE
Entity Column 명칭규칙 변경 제안

### ISSUE THREAD

**Issue by Belnut** [innovationacademy-kr/swlabs-helper#62]
Entity 관련 의견 여쭙고 싶습니다.
저번 회의에서 column 앞에 table명칭을 붙이는 건에 대해서 멘토님의 조언을 참고하여
column의 table 명칭을 다시 빼는 것이 어떨가 싶습니다.

이유로는 
1. jpa에서 직접 쿼리문을 작성하는 경우가 많지 않을 것이라 예상
2. 쿼리문을 작성 시 조인관련 에서 {table별칭.colmun}으로 사용하기 때문에 크게 헷갈리지 않을 것이라 예상
3. 기존방법 유지 시 entity의 모든 colmun에 name 옵션을 넣기 때문에 오타 발생 위험성 및 추가작업량 요구

가 있습니다.
여러분들 의견은 어떤가요?

**Comment by platanus-kr** [comment]
저는 이의 없습니다!

**Comment by epicarts** [comment]
저도 이의 없습니다!

**Comment by Belnut** [comment]
그러면 issue : #63 에서 동시에 변경해서 올리겠습니다!

**Comment by epicarts** [comment]
네 부탁드려요 :)
