### ISSUE TITLE
Logback 설정

### ISSUE THREAD

**Issue by platanus-kr** [innovationacademy-kr/swlabs-helper#75]
https://gofnrk.tistory.com/108
https://bamdule.tistory.com/29
로깅을 어짜피 해야한다면 Logback 설정을 해보겠습니다.

**Comment by epicarts** [comment]
현재 SLF4J 어노테이션을 사용하고 있는 것으로 알고 있는데 logback은 어떤 이점이 있나요?? (몰라서 물어보는 글입니다.)

**Comment by platanus-kr** [comment]
저도 잘 아는건 아닌데 우위나 잇점 보다는 slf4j 구현체가 Logback과 Log4j로 알고 있습니다 (log4j는 레거시 입니다)
그래서 지금 slf4j는 그냥 두고 Logback 설정만 만지면 로그 파일을 쉽게 뽑을 수 있을것 같아요
물론 해봐야 압니다 ㅠㅠ)ㅋㅋ

**Comment by epicarts** [comment]
그렇군요. 
쉽게 뽑아 낼 수 있으면, 추후 추가되었으면 좋겠다는 이슈로 S3와 같은 외부 저장소에 저장하는 방식으로 연결 시키는 것도 좋을 거 같습니다.
지금 서버는 끝나면 날아가서 영구적 저장소가 언젠간 필요하다고 생각해서요.

**Comment by platanus-kr** [comment]
별도의 설정을 하지 않아도 기본으로 날짜별 아카이빙을 하도록 되있어서 일단 보류하기로 했습니다
