### ISSUE TITLE
list_team page 구현

### ISSUE THREAD

**Issue by platanus-kr** [innovationacademy-kr/swlabs-helper#84]

**Comment by platanus-kr** [comment]
1. 담당 멘토 출력의 문제 - 이경우는 서비스에서 별도 처리를 해야 하나요?

**Comment by epicarts** [comment]
이슈보고 dto 에서 하나 가져올 수 있도록 만들어봤어요.
 
```
    public String getNicknameByMentor() {
        MemberRole memberRole = MemberRole.MENTOR;
        Optional<String> optional = Optional.of("empty");

        for (TeamMemberDto member : this.members) {
            if (memberRole.getName().equals(member.getMemberRole()))
                return member.getNickname();
        }
        return optional.get();
    }
```
가장 처음 발견한 Mento의 닉네임을 반환해주고, 만약 없을 경우 empty를 반환해줘요.

```
<td th:text="${team.getNicknameByMentor()}"></td>
```
 template 에는 이렇게 적으시면 됩니다.

https://github.com/epicarts/swlabs-helper/commit/cc1da56b1184154fd356ff408a20f2586c326218

**Comment by platanus-kr** [comment]
와이어프래임에 적힌 페이지 구현 요구사항에 뭔가 구멍이 있어서 일단 코멘트만 달아놓겠습니다

```
팀 목록: 내가 속해있지 않은 성사된 팀.
멘티 멘토가 성사되어 있는 팀.
멘티는 원하면 들어가서 팀을 선택하여 들어 갈 수 있다.
```

이렇게 되면 매칭되지 않은 (aka 멘토가 없는) 팀 목록은 어느 페이지에서도 확인할 수 없겠더라구요.
그래서 매칭된 팀을 따로 빼거나 필터링 옵션으로 넣더라도 우선 모든 팀이 다 나오는 기능을 구현하는게 맞는것 같다는 생각을 합니다.
이따 회의에서 다시 말씀드릴게요

**Comment by epicarts** [comment]
생각해보니 `내가 속해있지 않은 ` 조건도 붙네요.. 으아ㅏㅏ ㅏ
