### ISSUE TITLE
배포 스크립트 버그 수정

### ISSUE THREAD

**Issue by platanus-kr** [innovationacademy-kr/swlabs-helper#96]
현재 deploy 스크립트에서 java프로세스를 내리고 올리는 타이밍에 문제가 있음
sleep등의 딜레이가 필요한 상황

**Comment by platanus-kr** [comment]
스크립트 내 프로세스를 종료하는 kill 명령어에 대한 짧은 내용입니다
현재 스크립트에는 `15시그널`로 되어있는데 `15시그널`은 terminate 시그널이라 합니다. 현재 작업중인 메모리 작업들을 모두 sync하고 종료하게끔 작동한다네요.
일반적으로 프로세스를 강제종료할때는 `9 시그널`을 쓰는데 이건 프로세스가 무슨 작업중이든 간에 강제로 종료하는 시그널이라고 합니다. 따라서 작업중인 내역을 보장하지 않겠지요..

기존 문제는 15시그널로 짧은 시간 내에 프로세스가 내려가지 않는 문제가 있었습니다
시간이 좀 더 필요한것 같아 기존 5초에서 15초로 넉넉하게 둬볼려고 합니다.

관련 링크 : https://stackoverflow.com/a/55796920

**Comment by Belnut** [comment]
금일 2021-07-05 에 진행할 main 병합에 문제없으면 이슈를 닫겠습니다
